services:
  frontend:
    build: .
    init: true
    ports:
      - '127.0.0.1:5173:5173'
    env_file:
      - .env.docker
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
